<a href="https://colab.research.google.com/github/naeorii/estudos-analise-dados-python/blob/main/DataCleaningDuplicates.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

##**Duplicates**

Checking duplicates is extremely simple. It'll behave differently between Series and DataFrames. Let's start with Series.As an example, let's say we're throwing a fancy party and we're inviting Ambassadors from Europe. But you can only invite one ambassador per country. This is our original list, and as you can see, both UK and Germany have duplicated ambassadors:

In [2]:
ambassadors = pd.Series([
    'France',
    'United Kingdom',
    'United Kingdom',
    'Italy',
    'Germany',
    'Germany',
    'Germany',
], index=[
    'Gerard Araud',
    'Kim Darroch',
    'Peter Westmacott',
    'Armando Varricchio',
    'Peter Wittig',
    'Peter Ammon',
    'Klaus Scharioth'
])

In [3]:
ambassadors

Gerard Araud                  France
Kim Darroch           United Kingdom
Peter Westmacott      United Kingdom
Armando Varricchio             Italy
Peter Wittig                 Germany
Peter Ammon                  Germany
Klaus Scharioth              Germany
dtype: object

The two most important methods to deal with duplicates are `duplicated` (that will tell you which values are duplicates) and `drop_duplicates` (which will jjust get rid of duplicates):

In [5]:
ambassadors.duplicated() #quais valores são duplicados

Gerard Araud          False
Kim Darroch           False
Peter Westmacott       True
Armando Varricchio    False
Peter Wittig          False
Peter Ammon            True
Klaus Scharioth        True
dtype: bool

By default it'll consider the first occurence of the value as not-duplicate. You can change this behavior with the `keep `parameter:

In [7]:
ambassadors.duplicated(keep='last')  #the first ambassadors are considered duplicates

Gerard Araud          False
Kim Darroch            True
Peter Westmacott      False
Armando Varricchio    False
Peter Wittig           True
Peter Ammon            True
Klaus Scharioth       False
dtype: bool

You can also choose to mark all of them as duplicates with `keep=False`:

In [8]:
ambassadors.duplicated(keep=False)

Gerard Araud          False
Kim Darroch            True
Peter Westmacott       True
Armando Varricchio    False
Peter Wittig           True
Peter Ammon            True
Klaus Scharioth        True
dtype: bool

A similar method is` drop_duplicates`, which just excludes the duplicated values and also accepts the `keep `parameter:

In [9]:
ambassadors.drop_duplicates()

Gerard Araud                  France
Kim Darroch           United Kingdom
Armando Varricchio             Italy
Peter Wittig                 Germany
dtype: object

In [13]:
ambassadors.drop_duplicates(keep='last')

Gerard Araud                  France
Peter Westmacott      United Kingdom
Armando Varricchio             Italy
Klaus Scharioth              Germany
dtype: object

In [12]:
ambassadors.drop_duplicates(keep=False)

Gerard Araud          France
Armando Varricchio     Italy
dtype: object

##**Duplicates in DataFrames**

Conceptually speaking, duplicates in DataFRame happen at 'row' level. Two rows with exaclty the same values are considered to be duplicates:

In [14]:
players = pd.DataFrame({
    'Name': [
        'Kobe Bryant',
        'LeBron James',
        'Kobe Bryant',
        'Carmelo Anthony',
        'Kobe Bryant',
    ],
    'Pos': [
        'SG',
        'SF',
        'SG',
        'SF',
        'SF'
    ]
})

In [15]:
players

              Name Pos
0      Kobe Bryant  SG
1     LeBron James  SF
2      Kobe Bryant  SG
3  Carmelo Anthony  SF
4      Kobe Bryant  SF

Kobe is duplicated; but he appears with two different positions. What does `duplicated `say?

In [17]:
players.duplicated()

0    False
1    False
2     True
3    False
4    False
dtype: bool

"Duplicated means wall the column values should be duplicates. We can customize this with the `subset `parameter:

In [18]:
players.duplicated(subset=['Name'])

0    False
1    False
2     True
3    False
4     True
dtype: bool

And the same rules of `keep` still apply:

In [20]:
players.duplicated(subset=['Name'], keep='last')

0     True
1    False
2     True
3    False
4    False
dtype: bool

`drop_duplicates` takes the same parameters:

In [21]:
players.drop_duplicates()

              Name Pos
0      Kobe Bryant  SG
1     LeBron James  SF
3  Carmelo Anthony  SF
4      Kobe Bryant  SF

In [22]:
players.drop_duplicates(subset=['Name'])

              Name Pos
0      Kobe Bryant  SG
1     LeBron James  SF
3  Carmelo Anthony  SF

In [23]:
players.drop_duplicates(subset=['Name'], keep='last')

              Name Pos
1     LeBron James  SF
3  Carmelo Anthony  SF
4      Kobe Bryant  SF

---